# -*- coding: utf-8 -*-
"""atividade10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xAW3FQJodWSoOWs8YMg73p_x4IEckTx2
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.pyplot as plt
import numpy as np
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

# importando base de dados
a1_data = pd.read_csv("aula/aula21.csv", delimiter=',')
a1_data

kmeans = KMeans(n_clusters=2, random_state=0, n_init="auto").fit(a1_data)

centros = kmeans.cluster_centers_
centros

cluster_0 = centros[0]
cluster_1 = centros[1]

diferenca = np.abs(cluster_0 - cluster_1)
diferenca

atributos = [f'Atributo {i+1}' for i in range(len(diferenca))]
df_diferenca = pd.DataFrame({'Atributo': atributos, 'Diferença': diferenca})
df_diferenca = df_diferenca.sort_values(by='Diferença', ascending=False)

print(df_diferenca)

df = a1_data["a"] + a1_data["f"]
df['Cores'] = np.random.rand(len(df))

"""Os atributos com maior diferença são A e F, como é possível ver pelos valores obtidos acima."""

plt.scatter(a1_data["a"], a1_data["f"], c=df['Cores'], label='Dados')
plt.title('Gráfico de Dispersão de Dois Atributos')
plt.xlabel('Atributo 1')
plt.ylabel('Atributo 2')
plt.legend()
plt.grid(True)
plt.show()

kmeans = KMeans(n_clusters=7, random_state=0, n_init="auto").fit(a1_data)

centros = kmeans.cluster_centers_
centros

feature_pairs = [("a", "b"), ("a", "c"), ("a", "d"), ("a",
"e"), ("a", "f"),
 ("b", "c"), ("b", "d"), ("b", "e"), ("b",
"f"),
 ("c", "d"), ("c", "e"), ("c", "f"),
 ("d", "e"), ("d", "f"),
 ("e", "f")]

fig, axes = plt.subplots(nrows=5, ncols=3, figsize=(15, 20))
axes = axes.flatten()

for i, (attr1, attr2) in enumerate(feature_pairs):
    ax = axes[i]
    ax.scatter(a1_data[attr1], a1_data[attr2], alpha=0.7)
    ax.set_xlabel(attr1)
    ax.set_ylabel(attr2)
    ax.set_title(f'{attr1} vs {attr2}')
    ax.grid(True)

# Ajustar layout
plt.tight_layout()
plt.show()

"""O gráfico que apresenta uma diferença maior de resultados é o de a e f. Neste gráfico notamos que os dados parecem mais centrados em "núcleos". Alguns gráficos possuem os dados distribuídos de forma mais uniforme enquanto outros possuem dados esparsos no sentido horizontal ou vertical."""

a1_data_new = a1_data.iloc[:, [0, -1]]

kmeans = KMeans(n_clusters=7, random_state=0, n_init="auto").fit(a1_data_new)

centros = kmeans.cluster_centers_
centros

df = a1_data_new["a"] + a1_data_new["f"]
df['Cores'] = np.random.rand(len(df))

plt.scatter(a1_data["a"], a1_data["f"], c=df['Cores'], label='Dados')
plt.title('Gráfico de Dispersão de Dois Atributos')
plt.xlabel('Atributo 1')
plt.ylabel('Atributo 2')
plt.legend()
plt.grid(True)
plt.show()